### ISSUE TITLE
about script/SERVE_merge_QC.R 

### ISSUE THREAD

**Issue by dangsy** [janky-yz/SERVE#2]
Why is it that in mode=1, an input file for the subsequent step of GMAP is generated, which filters the transcripts based on their length, but after running GMAP, when running the R script in mode=2, the filtered GTF file based on transcript length is not used as input? Instead, the script uses the GTF file that was saved before the transcript length filtering. As a result, the generated file does not undergo transcript length filtering.
![Snipaste_2024-01-08_15-46-49](https://github.com/janky-yz/SERVE/assets/155949831/f0e1b447-7448-4a38-96a7-7a79cc1ba87d)

**Comment by janky-yz** [comment]
Thanks for the correction! We have updated the script.
